name: Parse Licenses

on:
  push:
    branches:
      - main

jobs:
  parse-licenses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Parse licenses
        run: |
          node -e "
          const fs = require('fs');
          const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          const licenses = Object.keys(packageJson.dependencies || {}).map(dep => {
            const pkg = require(dep + '/package.json');
            return { name: dep, license: pkg.license };
          });
          console.log(JSON.stringify(licenses, null, 2));
          "
